### PR TITLE
Fix bg color of table rows

### LINKED ISSUE #983: Light mode UI Hover background table row
On dark mode when we hover the rows of the pools table we get a background colour different than the main background but in light mode we get the same hover background colour as the main background making it kinda disappear.

## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

Hover background colour in light mode to be different than main background colour.

## Current Behavior

Hover background colour in light mode is the same as main background colour.

## Possible Solution

Change the hover background colour.

## Steps to Reproduce (for bugs)

1. Hover the pools table row in light mode

Screenshot 2021-02-26 at 15 22 07
Screenshot 2021-02-26 at 15 22 15

### PR DESCRIPTION
**Pull request by veado**
+ use observableState for themeType$

Fix #983

### CODE REVIEW

File: src/renderer/contexts/ThemeContext.tsx [hunk 1]
```diff
@@ -1,27 +1,45 @@
...
+  },
+  light: {
+    ...t.light,
+    // extend background colors - needed for bg of table rows
+    palette: { ...t.light.palette, background: [...t.light.palette.background, '#ededed'] }
+  }
+}
+
+console.log('t:', t)
+console.log('themes:', themes)
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/contexts/ThemeContext.tsx:30]: lets remove it :)

**Review by thatStrangeGuyThorchain — APPROVED** [review]
