### PR TITLE
use fatest fee when deposit

### LINKED ISSUE #1215: cannot estimate gas - display issue
ETH RUNE LP'ing 

OR={"REASON":"CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT","CODE":"UNPREDICTABLE_GAS_LIMIT","METHOD":"ESTIMATEGAS","TRANSACTION":{"FROM":"0XB078B4E8FA411B784E04A9DCC0E97D62F6A0759A","GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X14419AA600"},"TO":"0X9D496DE78837F5A2BA64CB40E62C19FBCB67F55A","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0DD610D89A7CE400"},"DATA":"0X1FECE7B4000000000000000000000000C5E3BC6DA47DCBFEAE8ADAA3BF6803857A1068E200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72313674676A713433307061787278393370637068336D656C7236676A6B716C373374657270706E0000000000000000"}}, TX={"DATA":"0X1FECE7B4000000000000000000000000C5E3BC6DA47DCBFEAE8ADAA3BF6803857A1068E200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72313674676A713433307061787278393370637068336D656C7236676A6B716C373374657270706E0000000000000000","TO":{},"GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X14419AA600"},"FROM":"0XB078B4E8FA411B784E04A9DCC0E97D62F6A0759A","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0DD610D89A7CE400"},"NONCE":{},"GASLIMIT":{},"CHAINID":{}}, CODE=UNPREDICTABLE_GAS_LIMIT, VERSION=ABSTRACT-SIGNER/5.0.10)

Screenshot 2021-03-29 at 12 23 30

## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

 testnet LP of ETH and RUNE

## Current Behavior

 Deposit Error

## Possible Solution

 perhaps a reminder note to leave ETH in wallet to provide for the ETH gas fees

## Steps to Reproduce (for bugs)

1. Deposit 100% testnet ETH and 100% testnet RUNE

2. slide to deposit

3. error message received

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version : macos
- Link to your project :

### PR DESCRIPTION
**Pull request by sarawut11**
fix #1215

### CODE REVIEW

File: src/renderer/services/chain/const.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const MAX_SWAP_STEPS = 3
  */
 export const FeeOptionKeys: { [key in TxTypes]: FeeOptionKey } = {
   SWAP: 'fast',
-  DEPOSIT: 'fast',
+  DEPOSIT: 'fastest',
```
Comment (veado) [inline src/renderer/services/chain/const.ts:21]: Change it in `depositFee$` for ETH  only (but not for others)

**Review by veado — CHANGES_REQUESTED** [review]

**Review by veado — APPROVED** [review]
Nice find + fix :+1:
