### PR TITLE
Fix chart data of PoolDetail

### LINKED ISSUE #1449: [PoolDetail] Invalid data
## Issue
Comparing data of `ETH.ETH` pool using `ASGARDEX` vs. `ThorSwap` there are some differences at some places:

- Chart (liquidity): y-axis has different values
- Fees are different
- Total txs are different
- etc.

## Screen shot (taken at 2021-05-25 16-38-04)
Screenshot from 2021-05-25 16-38-04

### PR DESCRIPTION
**Pull request by veado**
https://user-images.githubusercontent.com/61792675/119992491-e6b73f00-bfca-11eb-8b17-49683d97ea92.mp4

Fix #1449

### CODE REVIEW

File: src/renderer/views/pool/PoolChartView.tsx [hunk 1]
```diff
@@ -53,16 +65,40 @@ export const PoolChartView: React.FC<Props> = ({ priceRatio }) => {
...
+                getSwapHistory$({
+                  ...requestParams,
+                  interval: GetSwapHistoryIntervalEnum.Day
+                }),
+                getPoolLiquidityHistory$({
+                  ...requestParams,
+                  interval: GetLiquidityHistoryIntervalEnum.Day
+                })
+              ]).pipe(
+                RxOp.map(([swapHistoryRD, liquidityHistoryRD]) => sequenceTRD(swapHistoryRD, liquidityHistoryRD)),
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/views/pool/PoolChartView.tsx]: `liveData.sequenceS` ?

File: src/renderer/views/pool/PoolChartView.tsx [hunk 2]
```diff
@@ -53,16 +65,40 @@ export const PoolChartView: React.FC<Props> = ({ priceRatio }) => {
...
+
+                liveData.map(([swapHistory, _liquidityHistory]) =>
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/views/pool/PoolChartView.tsx]: `_liquidityHistory ` => `liquidityHistory `

**Review by thatStrangeGuyThorchain — CHANGES_REQUESTED** [review]
Nice. few suggestions
