### PR TITLE
use default fee in case of getfees failure

### LINKED ISSUE #628: [Epic] Use `default` fees in case of failure of `getFees`
Don't block any transaction form if fees could not be loaded. Whenever `getFees` might failed, call `getDefaultFees` of any `XChainClient` to get default fees.  

^ Depends on https://github.com/xchainjs/xchainjs-lib/issues/116

Following views / forms need to be updated:

- Send BTC
- Send BNB / BNC asset
- Send RuneNative
- Swap
- Deposit
- Withdraw

### PR DESCRIPTION
**Pull request by sarawut11**
closes #628

### CODE REVIEW

**Review by thatStrangeGuyThorchain — APPROVED** [review]

File: src/renderer/services/binance/fees.ts [hunk 1]
```diff
@@ -16,25 +17,31 @@ const { stream$: reloadFees$, trigger: reloadFees } = triggerStream()
...
-          (client) => Rx.from(client.getFees())
+          (client) => {
+            defaultFees = client.getDefaultFees()
+            return Rx.from(client.getFees())
+          }
         ),
         map(RD.success),
         startWith(RD.pending),
-        catchError((_) => Rx.of(RD.failure(Error('Error to load fees for BNB chain'))))
+        catchError((_) => Rx.of(RD.success(defaultFees)))
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/binance/fees.ts:38]: to keep things clearer i'd propose to get this value from the `oClient`
```ts
 catchError((_) => Rx.of(pipe(oClient, O.alt(() => new Client({}), O.map(client => client.getDefaultFees(), O.fold(() => RD.failure('error here'), RD.success)))) RD.success(defaultFees)))
 ```

**Review by veado — APPROVED** [review]
