### PR TITLE
[SWAP] send txs to the appropriate chain #679

### LINKED ISSUE #679: [SWAP] send txs to the appropriate chain
currently SwapView uses only BinanceContext to send txs. That is incorrect. We have to send any txs to the `sourceAsset.chain`  chain

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
LSS: get correct pool addresses for swap && get correct explorer url

- [x] `poolHelper.ts` removed `getDefaultRunePricePool`
- [x] replaced `BNB.Rune` assets for `getPoolTableRowData`. Now there are pools based on `RuneNative` only
- [x] added `src/renderer/services/chain/explorerUrl.ts` : `getExplorerUrlByAsset`
- [x] added `getExplorerTxUrl` to the thorchain service
- [x] passed chain-based transaction service to the the `ChainContext`
- [x] `SwapView`:  replaced `BinanceContext` for `ChainContext`
- [x] `SwapView`: replaced single `selectedPoolAddress$` to the 2 pool addresses (~source and target~ source asset's pool address, target asset's wallet address)

**Note**
~~until [fixed wrong assets comparission fix](https://github.com/xchainjs/xchainjs-lib/commit/0459aa13166a0ef77389c420d041d380990c7bcb) is not a part of published version of `xchain-thorcain` need to use locally built version.~~

known issues:

- ~for now we can not send swap txs with at RuneNative swap FROM RuneNative for testnet as https://testnet.midgard.thorchain.info/v2/thorchain/inbound_addresses does not contain THOR.RUNE at its response what leads that `sourcePoolAddress` can not be found in poolsAddresses list~ swap for THOR.RUNE is based on `ThorcainClient.deposit`
- wrong work for explorer urls of `RuneNative => AnyAsset` until [[xchain-thorchain] Make getExplorerUrl return url based on network #152](https://github.com/xchainjs/xchainjs-lib/issues/152) is resolved
- some problems with BTC client maybe @veado has any thoughts ? 
image

closes #679

### CODE REVIEW

File: src/renderer/services/chain/types.ts [hunk 1]
```diff
@@ -45,7 +45,10 @@ export type DepositFeesLD = LiveData<Error, DepositFees>
 
 export type SendDepositTxParams = { chain: Chain; asset: Asset; poolAddress: string; amount: BaseAmount; memo: Memo }
 
-export type SendTxParams = { asset: Asset; recipient: string; amount: BaseAmount; memo: Memo }
+// Allowed Tx types
+export type TxType = 'swap'
```
Comment (veado) [inline src/renderer/services/chain/types.ts:49]: `TxTypes.SWAP` ([code](https://github.com/thorchain/asgardex-electron/blob/0d879bf4b390c2eae437028f793036f698d8b060/src/renderer/types/asgardex.ts#L17-L22))

File: src/renderer/views/swap/SwapView.tsx [hunk 2]
```diff
@@ -114,19 +122,26 @@ export const SwapView: React.FC<Props> = (_): JSX.Element => {
     (source: Asset, amount: AssetAmount, memo: string) => {
       pipe(
         sourcePoolAddress,
+        O.alt(() => {
+          // For THOR chain we will send Deposit tx instead of
+          // plain ones. It does not need any additional address
+          if (source.chain === THORChain) {
```
Comment (veado) [inline src/renderer/views/swap/SwapView.tsx:128]: [nitpick] `eqChain` - just if you like ...

File: src/renderer/services/chain/transaction.ts [hunk 3]
```diff
@@ -45,8 +45,12 @@ const tx$ = ({ asset, recipient, amount, memo }: SendTxParams): TxLD => {
       // not available yet
       return txFailure$(`Tx stuff has not been implemented for ETH yet`)
 
-    case THORChain:
-      return THOR.sendTx({ recipient, amount, asset, memo })
+    case THORChain: {
+      if (txType === 'swap') {
```
Comment (veado) [inline src/renderer/services/chain/transaction.ts:49]: `TxTypes.SWAP` ?

**Review by veado — APPROVED** [review]
LGTM

**Comment by veado** [comment]
> some problems with BTC client maybe @veado has any thoughts ?

^ It will be fixed by [[Epic] Use `default` fees in case of failure of `getFees`](https://github.com/thorchain/asgardex-electron/issues/628) #628

**Review by veado — APPROVED** [review]
