### PR TITLE
[Deposit] Fix fees to depend on memo etc

### LINKED ISSUE #1027: [Deposit] Fix fees to depend on memo etc.
## Issue

Chain fees might based on amount, memo (BCH/LTC/BTC) or based on amount, memo, receipient(ETH), which needs to be addressed in `epositFees$`, `reloadFeesByChain` etc. in [services/chain/fees/deposit.ts](https://github.com/thorchain/asgardex-electron/blob/342cd39cf5d9e2ff85d3528971d7d84ca2676d6b/src/renderer/services/chain/fees/deposit.ts).

Also, DON'T [reload all fees at once for all chains](https://github.com/thorchain/asgardex-electron/blob/342cd39cf5d9e2ff85d3528971d7d84ca2676d6b/src/renderer/services/chain/fees/deposit.ts#L31-L36) - it needs to be fixed.

## Reference:

- Matrix of [Multichain fees](https://github.com/thorchain/asgardex-electron/issues/640) 
- Notes about [MULTICHAIN TXS + MEMOS + FEES](https://docs.google.com/document/d/1YkZ_51NNmFdGRQZmfwv6yWAO3BNjls8ssO_1L5gfqz8/edit#heading=h.mpcg7i4jfnb7)

- [Fix for `swapFee$`](https://github.com/thorchain/asgardex-electron/pull/1023/commits/8eafc43605b63ea96a7c7152869447207448ecc4#diff-3d7d6a9de441adfaeb62a2929d9272d03939c4ab4f7c44645f2077387f21513fR95-R112)

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
- fees/deposit.ts
--  `depositFees$` - refactored to receive parameters needed to calculate fees
-- `depositFeeByChain$` - refactored to receive parameters needed to calculate fees; refactored to get memo purely from parameters; added support for `ETH` fees

- ~`AsymDeposit.tsx` and `SymDeposit.tsx` upgraded to re-request in case chain or amount to deposit was changed. to avoid creation of multiple requests [`setDepositFees`](https://github.com/thorchain/asgardex-electron/pull/1033/files#diff-13b694da7eb491527fdeb8d2323767d9d0cbd39fcb4af79e1669b6b5c701cb3bR119) of `useObservableState`. simple usage of `useObservableState(() => dataStream$)` will have no any effect in case if deposit params were changed during component's lifecycle as [`useObservableState` will call the epic-like `init` function only once](https://github.com/crimx/observable-hooks/blob/master/packages/observable-hooks/src/use-observable-state.ts#L33) so for updating data for re-requesting fees [`useEffect` was used](https://github.com/thorchain/asgardex-electron/pull/1033/files#diff-13b694da7eb491527fdeb8d2323767d9d0cbd39fcb4af79e1669b6b5c701cb3bR146-R159)~
- added resetting amount to deposit in case changing asset and after finishing tx
- removed callback for reloading all fees. it was unused so this is safe remove
closes #1027

### CODE REVIEW

File: src/renderer/services/chain/fees/deposit.ts [hunk 1]
```diff
@@ -59,65 +62,120 @@ export const reloadFees$: Rx.Observable<O.Option<LoadFeesHandler>> = selectedPoo
   RxOp.map(O.map(reloadFeesByChain))
 )
 
-// State to reload deposit fees
-const { get$: reloadDepositFees$, set: reloadDepositFees } = observableState<DepositType>('asym')
+// Trigger stream to reload deposit fees
+const { stream$: reloadDepositFees$, trigger: reloadDepositFees } = triggerStream()
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/chain/fees/deposit.ts:66]: we create new streams in case chain or amount was changed so there is no need to handle `reloadDepositFees` with any parameters

File: src/renderer/components/deposit/add/AsymDeposit.tsx [hunk 2]
```diff
@@ -104,14 +112,34 @@ export const AsymDeposit: React.FC<Props> = (props) => {
...
+    [asset, assetAmountToDeposit, oMemo, oPoolAddress]
+  )
+
+  const [depositFeesRD] = useObservableState<DepositFeesRD>(() => chainFees$(depositFeesParams), RD.initial)
+
+  // reload fees whenever params have been changed
+  useEffect(() => {
+    reloadFees(depositFeesParams)
+  }, [depositFeesParams, reloadFees])
+
```
Comment (veado) [inline src/renderer/components/deposit/add/AsymDeposit.tsx:134]: Pls check latest changes of `swap$` - we reload fees **after** changing assets or input values (amount/memo) now. With it we avoid some uneeded requests to get fees. _It can be done with another PR..._

File: src/renderer/services/chain/fees/deposit.ts [hunk 3]
```diff
@@ -60,64 +57,136 @@ export const reloadFees$: Rx.Observable<O.Option<LoadFeesHandler>> = selectedPoo
...
+         */
+        return (
+          // Check if entered chain was changed
+          eqChain.equals(prev.asset.chain, next.asset.chain) &&
+          // Check if entered amount was changed
+          eqBaseAmount.equals(prev.amount, next.amount)
+        )
+      }
+      return false
+    }),
```
Comment (veado) [inline src/renderer/services/chain/fees/deposit.ts:151]: How about to provide a `eqDepositFeesParams` helper?

**Review by veado — DISMISSED** [review]
LGTM! Just two suggestions.

File: src/renderer/components/deposit/add/AsymDeposit.tsx (hunk 2 above)
Comment (thatStrangeGuyThorchain) [reply src/renderer/components/deposit/add/AsymDeposit.tsx:134]: yep. here is the same idea but in another place. at the `fees/deposit.ts` (your next comment) with `distinctUntilChanged`. just because deposit fees  are used in 2 separate places (sym+asym) it was moved to the service-layer to have the same logic for different places

File: src/renderer/services/chain/fees/deposit.ts (hunk 3 above)
Comment (thatStrangeGuyThorchain) [reply src/renderer/services/chain/fees/deposit.ts:151]: yeah. no problem. just as it used in a single place have not done it. will add it in few minutes

File: src/renderer/components/deposit/add/AsymDeposit.tsx (hunk 2 above)
Comment (thatStrangeGuyThorchain) [reply src/renderer/components/deposit/add/AsymDeposit.tsx:134]: created #1042

Comment (veado) [reply src/renderer/components/deposit/add/AsymDeposit.tsx:134]: `distinctUntilChanged  is good, but not enough. Imagine an user change his amount in the input field. With any small change, a request to load fees will be done. We can minimize such requests by adding a `onBlur` handler to the input to re-load fees only, if the user "leaves" the input.

Comment (veado) [reply src/renderer/components/deposit/add/AsymDeposit.tsx:134]: Resolved by #1044
