### PR TITLE
[SWAP] fix transaction data information #688

### LINKED ISSUE #688: [SWAP] fix transaction data information
currently we have getting of pool datas for multichain txs. it leads to wrong results showing to user
image

image

expected: results should be similar

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
closes #688

as we have now simple pricing for source and target assets it's not clear for user what this data is. this pr includes changing simple showing of assets prices to swap results based on selected price asset 

Including few tweaks:
- Remove box shadow from `transparent` button
- Remove `calResult` in favour of `slip`property
- Remove `visible` property
- Update stories for using latest storybook
- Remove `swap.state.pending` from i18n

### CODE REVIEW

File: src/renderer/components/swap/Swap.tsx [hunk 1]
```diff
@@ -316,43 +316,48 @@ export const Swap = ({
...
+                    assetToBase(assetAmount(changeAmount)),
+                    poolData[assetToString(sourceAssetWP.asset)],
+                    activePricePool.poolData
+                  )
+
+                return (
+                  <SwapModal
+                    key={'swap modal result'}
+                    basePriceAsset={activePricePool.asset}
+                    calcResult={{ slip: swapData.slip } as CalcResult}
```
Comment (veado) [inline src/renderer/components/swap/Swap.tsx:341]: Avoid such unsafe casting, since `{ slip: swapData.slip }` is not `CalcResult`! If `SwapModal` does need `{ slip: swapData.slip}` only, change its property `calcResult to `slip: BigNumber`.

**Review by veado — CHANGES_REQUESTED** [review]

File: src/renderer/components/swap/Swap.tsx (hunk 1 above)
Comment (veado) [reply src/renderer/components/swap/Swap.tsx:341]: Fix 505655a8a41e82159652a7a834516f568ed117ba

**Review by veado — APPROVED** [review]
