### PR TITLE
[Upgrade feature] State handling (incl. few other fixes)

### LINKED ISSUE #660: [RuneNative] Add upgrade feature
To upgrade `BNB.RUNE` -> `RUNE.RUNE`, provide a UI similar to send screen. 

- All amount of BNB.RUNE will be send
- An user **can't** add any amount or change an amount
- memo `SWITCH:thoraddress` (`thoraddress` -> address of ASGARD vault -> get it from /thorchain/inbound_addresses)

### PR DESCRIPTION
**Pull request by veado**
- [x] State handling `TxLD` in `AssetDetailView`
- [x] Rename `pushTx` -> `subscribeTx` / `sendDepositTx` -> `sendTx`
- [x] Fix `getWalletBalanceByAsset` + fix its tests
- [x] Add test for `isRuneNativeAsset`

Closes #660

### CODE REVIEW

File: src/renderer/components/wallet/assets/AssetDetails.tsx [hunk 1]
```diff
@@ -53,6 +56,22 @@ export const AssetDetails: React.FC<Props> = (props): JSX.Element => {
...
+  // unsubscribe of possible previous subscription of upgrade tx
+  // It will be called whenever state of `bnbTxSub` changed
+  useEffect(() => {
+    return () => {
+      FP.pipe(
+        bnbTxSub,
+        O.map((sub) => sub.unsubscribe())
+      )
+    }
+  }, [bnbTxSub])
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/components/wallet/assets/AssetDetails.tsx:73]: actually i still can not understand why you have decided to handle subscriptions at the View layer. 
why can not we use a subscriber-function from a service? (you have renamed it to the `subscribeTx`)

Comment (veado) [reply src/renderer/components/wallet/assets/AssetDetails.tsx:73]: The state of sending an upgrade tx is needed in `AssetDetails` only (to display it in tx modal). We don't need to store it "globally", because it's not be used anywhere else nor it's updated in a service by any other service (e.g. websocket service etc.) in this case. That was the only reason we have used this state globally before. 

A simple state handling in a component is just we do need here. If you have a case to store it globally, you can still use `subscribeTx`.
