### PR TITLE
Resolve: [Ledger] Enable upgrading BEP2.RUNE using Ledger

### LINKED ISSUE #1803: Upgrading BEP2.RUNE via Ledger is not working
When upgrading BEP2.RUNE, the flow successfully completes, but the upgrade is actually doesn't take place.

### PR DESCRIPTION
**Pull request by gromxyz**
Closes #1803

### CODE REVIEW

File: src/renderer/components/wallet/txs/upgrade/Upgrade.tsx [hunk 1]
```diff
@@ -115,7 +118,8 @@ export const Upgrade: React.FC<Props> = (props): JSX.Element => {
     () =>
       getWalletAssetAmountFromBalances(
         (balance) =>
-          eqString.equals(balance.walletAddress, walletAddress) && eqAsset.equals(balance.asset, runeAsset.asset)
+          eqString.equals(balance.walletAddress, walletAddress.toString()) &&
```
Comment (veado) [inline src/renderer/components/wallet/txs/upgrade/Upgrade.tsx]: Why `walletAddress.toString()`?

File: src/renderer/components/wallet/txs/upgrade/Upgrade.tsx [hunk 2]
```diff
@@ -126,7 +130,8 @@ export const Upgrade: React.FC<Props> = (props): JSX.Element => {
     () =>
       getWalletAssetAmountFromBalances(
         (balance) =>
-          eqString.equals(balance.walletAddress, walletAddress) && eqAsset.equals(balance.asset, chainBaseAsset)
+          eqString.equals(balance.walletAddress, walletAddress.toString()) &&
```
Comment (veado) [inline src/renderer/components/wallet/txs/upgrade/Upgrade.tsx]: Same question: Why `toString()`?

**Review by veado — CHANGES_REQUESTED** [review]

**Comment by veado** [comment]
Add `ledger` label (similar to SendView)

Screenshot from 2021-09-30 10-26-59

**Comment by veado** [comment]
No need to enter password by using Ledger

Screenshot from 2021-09-30 10-28-50

File: src/renderer/components/wallet/account/AccountSelector.styles.ts [hunk 3]
```diff
@@ -52,5 +52,5 @@ export const Label = styled(UILabel).attrs({
 `
 
 export const WalletTypeLabel = styled(WalletTypeLabelUI)`
-  margin: -45px 0px 0px 10px;
+  margin: -20px 0px 0px 10px;
```
Comment (veado) [inline src/renderer/components/wallet/account/AccountSelector.styles.ts:55]: This change will effect SendView as well (as discussed in DM) - will be fixed with another PR

Screenshot from 2021-09-30 11-04-17

**Review by veado — APPROVED** [review]
