### PR TITLE
Fix error handling of Byzantine #306

### LINKED ISSUE #306: Fix error handling of Byzantine
By switching between `mainnet` <-> `testnet` the stream of `$endpoint` will be closed if an error occurs, but we still have to do another request by next switch of `mainnet` <-> `testnet`.

## Example:

- _Switch to Testnet:_ Request of https://testnet-seed.thorchain.info/node_ip_list.json succeeded
- _Switch to Mainnet:_ Request of https://seed.thorchain.info/node_ip_list.json failed (because this endpoint is not implemented yet)
- _Another switch to Testnet:_ Request of https://testnet-seed.thorchain.info/node_ip_list.json does not happen anymore

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
closes #306

### CODE REVIEW

File: src/renderer/helpers/rx/index.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export * from './fromPromise'
```
Comment (veado) [inline src/renderer/helpers/rx/index.ts:1]: Pls don't create a file for just a single helper function ^. Just put `fromPromise` into a file in `src/renderer/helpers/rx.ts`, which will avoid to mess up with too many of files in our repo.

File: src/renderer/helpers/rx/liveData.ts [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+} from '@devexperts/utils/dist/typeclasses/product-left-coproduct-left/product-left-coproduct-left.utils'
+import { sequenceT } from 'fp-ts/lib/Apply'
+import { array } from 'fp-ts/lib/Array'
+import { Filterable2 } from 'fp-ts/lib/Filterable'
+import { MonadThrow2 } from 'fp-ts/lib/MonadThrow'
+import { pipeable } from 'fp-ts/lib/pipeable'
+import { Observable } from 'rxjs'
+
+/**
+ * isomoprhic to `LiveData12<typeof instanceObservable.URI, typeof remoteData.URI, E, A>`
```
Comment (veado) [inline src/renderer/helpers/rx/liveData.ts:17]: What is `LiveData12`? 

[nitpick] small typo `isomoprhic`

File: src/renderer/services/midgard/service.ts [hunk 3]
```diff
@@ -263,16 +272,11 @@ const { stream$: reloadNetworkInfo$, trigger: reloadNetworkInfo } = triggerStrea
  */
 const networkInfo$: Rx.Observable<NetworkInfoRD> = reloadNetworkInfo$.pipe(
   // start request
-  switchMap((_) => loadNetworkInfo$()),
+  switchMap(loadNetworkInfo$),
```
Comment (veado) [inline src/renderer/services/midgard/service.ts:275]: Nice catch!
