### PR TITLE
Show `ledger` label in `InteractView` + fix styles

### LINKED ISSUE #1747: [AssetDetails] Fix position of `ledger` label in mobile view
Screenshot from 2021-09-10 10-33-12

It should be similar to SendView :arrow_down: 

Screenshot from 2021-09-10 10-35-32

### LINKED ISSUE #1748: [InteractView] Add `ledger` label

### PR DESCRIPTION
**Pull request by veado**
## [InteractView] Add `ledger` label

Screenshot from 2021-09-10 11-58-10

Screenshot from 2021-09-10 11-57-53

Fix #1748

## [AssetDetails] Fix `ledger` label in mobile view

Screenshot from 2021-09-10 11-46-29

Fix #1747

### CODE REVIEW

File: src/renderer/services/const.ts [hunk 1]
```diff
@@ -5,7 +5,8 @@ import { Network } from '../../shared/api/types'
 import { envOrDefault } from '../helpers/envHelper'
 import { SlipTolerance } from '../types/asgardex'
 
-export const DEFAULT_NETWORK: Network = 'mainnet'
+// export const DEFAULT_NETWORK: Network = 'mainnet'
+export const DEFAULT_NETWORK: Network = 'testnet'
```
Comment (veado) [inline src/renderer/services/const.ts]: Revert it ^

**Review by gromxyz — APPROVED** [review]
