### PR TITLE
fix pool shares data mismatch issue

### LINKED ISSUE #1072: [ETH] Pool shares
Make sure ETH/ERC20 are listed in pool shares

### PR DESCRIPTION
**Pull request by sarawut11**
closes #1072

### CODE REVIEW

File: src/renderer/services/midgard/pools.ts [hunk 1]
```diff
@@ -218,7 +219,7 @@ const createPoolsService = (
   }
 
   // Factory to create a stream to get data of `AssetDetails`
-  const getAssetDetails$: (poolAssets$: PoolAssetsLD, status: GetPoolsStatusEnum) => PoolAssetDetailsLD = (
+  const getAssetDetails$: (poolAssets$: PoolAssetsLD, status?: GetPoolsStatusEnum) => PoolAssetDetailsLD = (
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:222]: Same here: No need to have `status` optional. It's not used anywhere...

File: src/renderer/services/midgard/pools.ts [hunk 2]
```diff
@@ -179,7 +180,7 @@ const createPoolsService = (
   /**
    * Data of `AssetDetails` from Midgard
    */
-  const apiGetAssetInfo$: (assetOrAssets: string | string[], status: GetPoolsStatusEnum) => PoolAssetDetailsLD = (
+  const apiGetAssetInfo$: (assetOrAssets: string | string[], status?: GetPoolsStatusEnum) => PoolAssetDetailsLD = (
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:183]: No need to have `status` optional. It's not used anywhere...

File: src/renderer/services/midgard/pools.ts [hunk 3]
```diff
@@ -255,6 +256,39 @@ const createPoolsService = (
       RxOp.shareReplay(1)
     )
 
+  /**
+   * Loading queue to get all needed data for `AllPoolsState`
+   */
+  const loadAllPoolsStateData$ = (): AllPoolsStateLD => {
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:262]: `AllPoolsStateLD` -> `PoolDetailsLD`

File: src/renderer/services/midgard/pools.ts [hunk 4]
```diff
@@ -255,6 +256,39 @@ const createPoolsService = (
...
+      // Filter out all unknown / invalid assets created from asset strings
+      liveData.map(A.filterMap(({ asset }) => FP.pipe(asset, assetFromString, O.fromNullable))),
+      // Filter pools by using enabled chains only (defined via ENV)
+      liveData.map(A.filter(({ chain }) => isEnabledChain(chain))),
+      RxOp.shareReplay(1)
+    )
+    const poolDetails$ = getPoolDetails$(poolAssets$)
+
+    return FP.pipe(
+      liveData.sequenceS({
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:274]: `sequenceS` is not needed here (there is just one stream to handle, `sequenceXYZ` is used for more than one...)

File: src/renderer/services/midgard/types.ts [hunk 5]
```diff
@@ -67,6 +67,12 @@ export type PendingPoolsState = {
 export type PendingPoolsStateRD = RD.RemoteData<Error, PendingPoolsState>
 export type PendingPoolsStateLD = LiveData<Error, PendingPoolsState>
 
+export type AllPoolsState = {
+  poolDetails: PoolDetails
+}
+export type AllPoolsStateRD = RD.RemoteData<Error, AllPoolsState>
+export type AllPoolsStateLD = LiveData<Error, AllPoolsState>
```
Comment (veado) [inline src/renderer/services/midgard/types.ts:74]: Can be removed (see previous comment at `loadAllPoolsDetails`

File: src/renderer/services/midgard/pools.ts [hunk 6]
```diff
@@ -255,6 +256,39 @@ const createPoolsService = (
...
+      }),
+      RxOp.startWith(RD.pending),
+      RxOp.catchError((error: Error) => Rx.of(RD.failure(error)))
+    )
+  }
+
+  /**
+   * State of all pool data
+   */
+  const allPoolsState$: AllPoolsStateLD = reloadPools$.pipe(
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:285]: `AllPoolsStateLD` -> `PoolDetailsLD`

**Review by veado — CHANGES_REQUESTED** [review]

**Review by veado — APPROVED** [review]
