### PR TITLE
update xchain-eth lib and minor ui fix

### LINKED ISSUE #982: ERC20 token tx history data fix
image
a part of #965

### PR DESCRIPTION
**Pull request by sarawut11**
closes #982

### CODE REVIEW

File: src/renderer/components/uielements/assets/assetInfo/AssetInfo.tsx [hunk 1]
```diff
@@ -151,7 +151,7 @@ export const AssetInfo: React.FC<Props> = (props): JSX.Element => {
         <Styled.CoinSubtitle>
           {FP.pipe(
             oAsset,
-            O.map(assetToString),
+            O.map((asset) => asset.chain),
```
Comment (veado) [inline src/renderer/components/uielements/assets/assetInfo/AssetInfo.tsx:154]: Pls use a more bright color for `CoinSubtitle` comparing to `CoinTitle`

**Review by veado — CHANGES_REQUESTED** [review]

**Review by veado — APPROVED** [review]
