### PR TITLE
Fix ERC20 assets for testnet

### LINKED ISSUE #1788: UST and XRUNE balances do not show up in testnet wallet
## Prerequisites
Have either UST or XRUNE in your testnet wallet or swap for them

## Expected Behavior
Actual available balance should show like for other assets

## Current Behavior
Assets do not show in wallet at all or while attempting to make swaps
These screenshots are from the same wallet on SKIP and ASGARDEX Desktop respectively
image
image

## Steps to Reproduce

1. Transfer or swap XRUNE or UST to your testnet wallet
2. Verify they are the assets are in your wallet (use etherscan or SKIP testnet). 
3. Refresh your ASGARDEX wallet and verify the assets are not showing up

## Your Environment - Release Version (skip if not using a release version)
v0.4.0 Desktop on multiple OS

### PR DESCRIPTION
**Pull request by veado**
Some background information here: https://github.com/thorchain/asgardex-electron/issues/1788#issuecomment-927153720

Screenshot from 2021-09-25 19-17-23

Fix #1788

### CODE REVIEW

File: src/renderer/const.ts [hunk 1]
```diff
@@ -34,10 +36,17 @@ export const AssetXRune: Asset = {
 
 export const AssetXRuneTestnet: Asset = {
   chain: ETHChain,
-  symbol: 'XRUNE-0x0fE3ecd525D16fA09aA1FF177014dE5304c835E2',
+  symbol: 'XRUNE-0x8626db1a4f9f3e1002eeb9a4f3c6d391436ffc23',
   ticker: 'XRUNE'
 }
 
+// ETH.UST
```
Comment (gromxyz) [inline src/renderer/const.ts]: Is this UST for testnet only? (If yes, maybe just a comment would be useful here)

**Review by gromxyz — DISMISSED** [review]
👍

**Review by gromxyz — APPROVED** [review]
