### PR TITLE
Resolve: Whitelist pending transactions recovery link

### LINKED ISSUE #1804: Link for recovering transactions doesn't work on testnet
https://testnet.thorswap.finance/pending
Doesn't open from asgardex, needs to be whitelisted

Screenshot 2021-09-29 at 20 05 51

### PR DESCRIPTION
**Pull request by gromxyz**
Closes #1804

### CODE REVIEW

File: src/main/api/url.ts [hunk 1]
```diff
@@ -23,6 +23,8 @@ const EXTERNALS_WHITELIST = [
   'tltc.bitaps.com',
   'ltc.bitaps.com',
   'www.blockchain.com',
+  'testnet.thorswap.finance',
+  'testnet.thorswap.finance',
   'testnet.asgard.exchange',
   'app.asgard.exchange',
```
Comment (veado) [inline src/main/api/url.ts]: Can you remove these with this PR as well?

**Review by veado — CHANGES_REQUESTED** [review]

**Review by veado — APPROVED** [review]
