### PR TITLE
Fix (and simplify) price handling

### LINKED ISSUE #316: Fix default value for `selectedPricePoolAsset$`
Symbols are different for main- / testnet:

## RUNE

- Testnet `PoolAsset.RUNE67C`
- Mainnet `PoolAsset.RUNEB1A`

## TUSDB
(^ is not a default value, but needs to be updated as well)
- Testnet `PoolAsset.TUSD5D7 = TUSD-5D7`
- Mainnet `PoolAsset.TUSDB888 = TUSDB-888`

## Links
- Testnet tokens https://testnet-dex.binance.org/api/v1/tokens?limit=1000
- Mainnet tokens https://dex.binance.org/api/v1/tokens?limit=1000

### LINKED ISSUE #490: Wallet: Fix price calculation in assets table

### PR DESCRIPTION
**Pull request by veado**
- [x] Fix price calculation in wallets asset table
- [x] Remove `CURRENCY_SYMBOLS` in favour of using `asgardex-util` helper `currencySymbolByAsset` ([see MR 18](https://gitlab.com/thorchain/asgardex-common/asgardex-util/-/merge_requests/18))
- [x] Remove `RUNE_PRICE_POOL` in favour of using `getDefaultRunePricePool` helper
- [x] Remove `RUNEAsset` type (we will use `isRuneAsset` helper if needed)
- [x] Remove `PoolAsset` enum, we used almost everywhere. From now we use `Assets` only.
- [x] Remove `CommonAssets`, `commonAssets`, networkPools`, `mapNetworkToPoolAssets` (no need to have such things anymore...)
- [x] Update handling + usage of `runeAsset$` (incl. `getDefaultRuneAsset`)
- [x] Add `getRunePricePool` depending on selected network
- [x] Fix style of Network menu icon in wallets `Settings`
- [x] Use more types in services & Co.
- [x] All depending tests have been updated

Fix #490
Fix #316

### CODE REVIEW

File: src/renderer/helpers/assetHelper.ts [hunk 1]
```diff
@@ -65,9 +70,13 @@ export const isBtcAsset = (asset: Asset): boolean => eqAsset.equals(asset, Asset
...
 export const isEthAsset = (asset: Asset): boolean => eqAsset.equals(asset, AssetETH)
 
-export const getCurrencySymbolByAssetString = (asset: string) => {
-  if (asset in CURRENCY_SYMBOLS) {
-    return CURRENCY_SYMBOLS[asset as keyof typeof CURRENCY_SYMBOLS]
-  }
-  return assetFromString(asset)?.ticker || ''
-}
+/**
+ * Check whether an asset is a RUNE asset
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/helpers/assetHelper.ts:74]: seems this check is not for RUNE :)

File: src/renderer/services/midgard/pools.ts [hunk 2]
```diff
@@ -168,36 +179,43 @@ const createPoolsService = (
...
    */
-  const selectedPricePoolAssetSymbol$ = FP.pipe(
-    selectedPricePoolAsset$,
-    map(
-      FP.flow(
-        O.map(getCurrencySymbolByAssetString),
-        O.getOrElse(() => '')
-      )
+  const selectedPricePoolAssetSymbol$: Rx.Observable<O.Option<string>> = selectedPricePoolAsset$.pipe(
+    map(FP.flow(O.map(currencySymbolByAsset)))
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/midgard/pools.ts:199]: seems we dont need `flow` here anymore

File: src/renderer/views/stake/Share/ShareView.tsx [hunk 3]
```diff
@@ -40,7 +46,11 @@ export const ShareView: React.FC<{ asset: Asset }> = ({ asset }) => {
             target={asset.chain}
             poolShare={helpers.getPoolShare(stake, pool)}
             assetStakedShare={assetStakedShare}
-            basePriceAsset={priceSymbol}
+            // TODO (@thatThorchainGuy) price symobl as `basePriceAsset` - is that correct?
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/views/stake/Share/ShareView.tsx:49]: yep. thats correct. agree thats this is a little bit confusing name. previously there was an asset at the `PoolCard` component but was replaced to the asset's symbol itself which is calculated at the midgard service as a single source of thruth

**Review by thatStrangeGuyThorchain — APPROVED** [review]
