### PR TITLE
Fix 404 errors by requesting for asset icons

### LINKED ISSUE #895: Release V0.0.4 - page load caused 404 on png
- [ ] Using yarn dev
- [ ] Using node 12.14.4
- [ ] Using an up-to-date Release V0.0.4

## Expected Behavior
Pool page loads without any error console errors

## Current Behavior
Every time the pool page is loaded, or Refresh button is pressed a 404 is produced. This happens when entering and existing a pool. 

https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/binance/assets/BUSD-BAF/logo.png 

image

## Possible Solution
Update the call to where the png is located. 

## Steps to Reproduce (for bugs)

1. Create wallet

2. Go to the pools area

3. Move into a pool (any) via + Liquidity Button

4. Same occurs when pressing the back button

### PR DESCRIPTION
**Pull request by junkai121**
Fix #895

### CODE REVIEW

File: src/renderer/components/uielements/assets/assetIcon/AssetIcon.tsx [hunk 1]
```diff
@@ -19,6 +31,9 @@ type ComponentProps = {
 type Props = ComponentProps & React.HTMLAttributes<HTMLDivElement>
 
 export const AssetIcon: React.FC<Props> = ({ asset, size = 'normal', className = '', ...rest }): JSX.Element => {
+  const { network$ } = useAppContext()
+  const network = useObservableState<Network>(network$, DEFAULT_NETWORK)
```
Comment (veado) [inline src/renderer/components/uielements/assets/assetIcon/AssetIcon.tsx:35]: Pls provide network as parameter. We have a rule (you might not know it): Access any `XYZContext` in `XYZViews` only (but not in components).

**Review by veado — CHANGES_REQUESTED** [review]
Pls update stories to provide examples for current chains (`ETH` incl. ERC20, `BNB`, `BTC`) for mainnet + testnet.

**Review by veado — APPROVED** [review]
Well done!
