### PR TITLE
Fix loading state for RUNE price in header

### LINKED ISSUE #1482: [Header] RUNE price shows wrong value by re-loading data
Peek 2021-06-01 11-01

### PR DESCRIPTION
**Pull request by veado**
- [x] Fix loading state for RUNE price in header
- [x] Introduce `useRunePrice` hook

Peek 2021-06-01 10-54

Fix #1482

### CODE REVIEW

File: src/renderer/components/header/stats/HeaderStats.tsx [hunk 1]
```diff
@@ -1,54 +1,63 @@
...
+                trimZeros: true,
+                decimal: isUSDAsset(asset) ? 2 : 6
+              })
+            ),
+            O.map((label) => {
+              // store price label
+              prevRunePriceLabel.current = label
+              return label
+            }),
+            O.getOrElse(() => '')
```
Comment (veado) [inline src/renderer/components/header/stats/HeaderStats.tsx]: In case of no price, it should be `--` ^

File: src/renderer/hooks/useRunePrice.types.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+import * as RD from '@devexperts/remote-data-ts'
+import * as O from 'fp-ts/lib/Option'
+
+import { AssetWithAmount } from '../types/asgardex'
+
+export type RunePriceRD = RD.RemoteData<Error, O.Option<AssetWithAmount>>
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/hooks/useRunePrice.types.ts]: not sure that i understand why we need option inside ?

File: src/renderer/views/pools/Pools.types.ts [hunk 3]
```diff
@@ -22,6 +24,9 @@ export type PricePool = {
   poolData: PoolData
 }
 
+export type PricePool$ = Rx.Observable<PricePool>
+export type PricePoolRD = RD.RemoteData<Error, PricePool>
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/views/pools/Pools.types.ts]: hm. this time i could not fins usage of `PricePoolRD` 😅

File: src/renderer/hooks/useRunePrice.types.ts (hunk 2 above)
Comment (veado) [reply src/renderer/hooks/useRunePrice.types.ts]: Price might not be available in case there is no price pool or there is no selected price asset.

File: src/renderer/views/pools/Pools.types.ts (hunk 3 above)
Comment (veado) [reply src/renderer/views/pools/Pools.types.ts]: Yeah, that happens if you tried to solve that issue, but using a different way before :sweat_smile:

File: src/renderer/hooks/useRunePrice.types.ts (hunk 2 above)
Comment (thatStrangeGuyThorchain) [reply src/renderer/hooks/useRunePrice.types.ts]: yep. but is not `RD.initial` enough in this case ?
- `initial` : no data provided
- `pending`: loading data
- `error`: error data fetching
- `success`: show data
?

Comment (veado) [reply src/renderer/hooks/useRunePrice.types.ts]: ^ solved by @thatStrangeGuyThorchain :eye:  a1c50638f119bdb30c5ff6f81adef3cfd9c5a5f3
