### PR TITLE
Fix deposit BTC fee for using memo

### LINKED ISSUE #549: Add deposit: Change BTC fee to base on memo

### PR DESCRIPTION
**Pull request by veado**
- [x] Fix deposit BTC fee for using memo
- [x] Add `isBtcChain` helper
- [x] Add tests for all `chainHelpers`

Close #549

### CODE REVIEW

File: src/renderer/services/chain/memo.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import { selectedPoolAsset$ } from '../midgard/common'
+import { baseAddress$ } from './address'
+import { MemoRx } from './types'
+
+/**
+ * Stake memo
+ */
+const stakeMemo$: MemoRx = Rx.combineLatest([selectedPoolAsset$, baseAddress$]).pipe(
+  RxOp.switchMap(([oPoolAsset, oBaseAddress]) =>
+    Rx.of(
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/chain/memo.ts:19]: do we actually need this ? 
why not just `RxOp.map` instead of `RxOp.switchMap` ?

File: src/renderer/services/chain/memo.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+      FP.pipe(
+        sequenceTOption(oPoolAsset, oBaseAddress),
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/chain/memo.ts:21]: `sequenceTOption` will fall into `None`  value if one of element is `None`. im not sure here but what about scenario when we dont really need `oBaseAddress ` ? example
* oPoolAsset is asse from `BASE_CHAIN`
* oBaseAddress === O.none

in case of BASE_CHAIN we dont need on address anyway. 
do i miss anything ?

File: src/renderer/services/chain/address.ts [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+const crossAddress$: AddressRx = selectedPoolChain$.pipe(
+  RxOp.switchMap((oChain) =>
+    FP.pipe(
+      oChain,
+      // x-chain only
+      O.filter((chain) => !eqChain.equals(chain, BASE_CHAIN)),
+      O.fold(() => Rx.of(O.none), addressByChain$)
+    )
+  ),
+  RxOp.distinctUntilChanged()
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/chain/address.ts:39]: as an inner value is an ADT (in this case Option) such usage of `distinctUntilChanged` will affect nothing as there are always new pointers. this should be
```ts
RxOp.distinctUntilChanged(eqOString.equals)
```

File: src/renderer/services/chain/address.ts [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+)
+
+/**
+ * Users wallet address for base chain
+ */
+const baseAddress$: AddressRx = addressByChain$(BASE_CHAIN).pipe(RxOp.distinctUntilChanged())
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/chain/address.ts:45]: same here

File: src/renderer/services/chain/memo.ts (hunk 2 above)
Comment (veado) [reply src/renderer/services/chain/memo.ts]: Good questions + good point :+1: ! You are right, for deposits of base-chain assets, we don't need to add an address to memo. But in case of x-chain deposit we have to. Current implementation does not reflect all scenarios, I have fixed with 8cb51e2

**Review by thatStrangeGuyThorchain — DISMISSED** [review]
