### PR TITLE
Fix data handling for pool shares

### LINKED ISSUE #830: [BTC] Pool share are not displayed
in ADD / WITHDRAW screens. Currently, [member endpoint](https://testnet.midgard.thorchain.info/v2/member/) is called by users BNB (but not BTC) address

### LINKED ISSUE #832: Check out midgard stake service api$ mappings
check it out based on https://github.com/thorchain/asgardex-electron/pull/831#discussion_r569657012

### PR DESCRIPTION
**Pull request by veado**
- [x] Update `getStakes$` by accepting `address`+ `asset` via props (not streams)
- [x] Update story of `Deposit`
- [x] Quick fix of test for `getPoolShare`

Fix #830 
Fix #832

### CODE REVIEW

File: src/renderer/services/midgard/stake.ts [hunk 1]
```diff
@@ -29,54 +24,55 @@ const createStakeService = (
...
+            () => Rx.EMPTY,
+            (api) =>
+              FP.pipe(
+                api.getMemberDetail({ address }),
+                RxOp.map(({ pools }) => pools),
+                RxOp.map(A.findFirst((poolDetails) => poolDetails.pool === assetToString(asset)))
+              )
+          )
+        ),
+        RxOp.map(O.fold(() => RD.initial, RD.success)),
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/midgard/stake.ts:44]: hmmmm. i see that this is previous implementation but not sure that i fully understand what's going on😅 why so complicated ?
maybe just use `liveData` ?
```ts
 api$.pipe(
        liveData.chain((api) =>
          FP.pipe(
            api.getMemberDetail({ address }),
            RxOp.map(RD.success),
            liveData.map(({ pools }) => pools),
            liveData.chain(
              FP.flow(
                A.findFirst((poolDetails) => poolDetails.pool === assetToString(asset)),
                liveData.fromOption(() => Error('No pool'))
              )
            )
          )
        ),
        liveData.map((poolDetails) => ({...
```

**Review by thatStrangeGuyThorchain — APPROVED** [review]

File: src/renderer/services/midgard/stake.ts (hunk 1 above)
Comment (veado) [reply src/renderer/services/midgard/stake.ts]: Done 2e2851c
