### PR TITLE
Fix increasing numbers of requests for balances

### LINKED ISSUE #1785: [Wallet] Too many requests for same endpoint
## Issue 1

After adding a Ledger for BNB, https://testnet-dex.binance.org/api/v1/account/{address} is called many times and number of calls are increasing. All on branch `issue-1772/sign-bnb-transactions-ledger`

https://user-images.githubusercontent.com/61792675/134226353-f88e8550-4e19-4872-8f68-df939c9a92f6.mp4

## Issue 2

Same for RUNE

https://user-images.githubusercontent.com/61792675/134226694-58244259-bdb1-4a77-89c4-8082bfd9bd69.mp4

### PR DESCRIPTION
**Pull request by veado**
- [x] Fix increasing numbers of requests for balances
- [x] Fix state of `balances` to consider `Ledger` balances, too
- [x] Re-enable BNB Ledger

Fix #1785

### CODE REVIEW

File: src/renderer/services/wallet/balances.ts [hunk 1]
```diff
@@ -143,17 +143,17 @@ export const createBalancesService = ({
    * to give to the user last balances he loaded without re-requesting
    * balances data which might be very expensive.
    */
-  let walletBalancesState: Partial<Record<Chain, WalletBalancesRD>> = {}
+  const walletBalancesState: Map<{ chain: Chain; walletType: WalletType }, WalletBalancesRD> = new Map()
```
Comment (veado) [inline src/renderer/services/wallet/balances.ts:146]: Now we store balances of `keystore` and `Ledger` balances

File: src/renderer/services/wallet/balances.ts [hunk 2]
```diff
@@ -340,19 +342,21 @@ export const createBalancesService = ({
...
+        ETH: [ethChainBalance$],
+        BNB: [bnbChainBalance$, bnbLedgerChainBalance$],
+        LTC: [litecoinBalance$]
+      })
+    ),
     // we ignore all `ChainBalances` with state of `initial` balances
     // (e.g. a not connected Ledger )
-    RxOp.map(A.filter(({ balances }) => !RD.isInitial(balances)))
+    RxOp.map(A.filter(({ balances }) => !RD.isInitial(balances))),
+    RxOp.shareReplay(1)
```
Comment (veado) [inline src/renderer/services/wallet/balances.ts:359]: This `shareReplay` here avoid increasing numbers of requests for balances, which happened before by any new subscription to `chainBalances$`

**Review by gromxyz — APPROVED** [review]
👍
