### PR TITLE
Fix create view error UX flow

### LINKED ISSUE #1460: Wallet Creation-When "Finish" is selected nothing happens?
## Prerequisites

- [x] Using yarn
- [x] Using node 12.x
- [x] Using the latest release or an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [x] Link to stacktrace in a Gist (for bugs)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
clarified create mnemonic component:
- Added missed error for invalid entered phrase
- decreased opacity for already entered word
image
image

closes #1460

### CODE REVIEW

File: src/renderer/i18n/de/wallet.ts [hunk 1]
```diff
@@ -44,6 +44,7 @@ const wallet: WalletMessages = {
   'wallet.create.words.click': 'Klicke die Wörter in der richtigen Reihenfolge',
   'wallet.create.creating': 'Erstelle eine Wallet ...',
   'wallet.create.error': 'Fehler beim Abspeichern der Phrase',
+  'wallet.create.error.phrase': 'Save your phrase safely and enter it in a correct way - DE',
```
Comment (veado) [inline src/renderer/i18n/de/wallet.ts]: 'wallet.create.error.phrase': 'Speicher Deine Phrase an einem sicheren Ort und gebe diese in der richtigen Reihenfolge ein',

File: src/renderer/i18n/en/wallet.ts [hunk 2]
```diff
@@ -41,6 +41,7 @@ const wallet: WalletMessages = {
   'wallet.create.copy.phrase': 'Copy phrase below',
   'wallet.create.title': 'Create new wallet',
   'wallet.create.enter.phrase': 'Enter phrase correctly',
+  'wallet.create.error.phrase': 'Save your phrase safely and enter it in a correct way',
```
Comment (veado) [inline src/renderer/i18n/en/wallet.ts]: `Save your phrase at a safety place and enter it in a correct way`

**Review by veado — CHANGES_REQUESTED** [review]
Could you change the error text as follow (I could not find the styles for in changes of this PR):
- All in uppercase
- More padding / margin to bottom (as similar as it's for to the top)

**Review by veado — APPROVED** [review]
