### PR TITLE
fix eth pricing in assets view

### LINKED ISSUE #961: [ETH] Wrong pricing for ETH in assets overview
:eyes: $ 93,839,104,811.967 :arrow_down: 

Screenshot from 2021-02-22 19-04-20

### PR DESCRIPTION
**Pull request by sarawut11**
closes #961

### CODE REVIEW

File: src/renderer/components/wallet/assets/AssetsTableCollapsable.tsx [hunk 1]
```diff
@@ -145,7 +145,12 @@ export const AssetsTableCollapsable: React.FC<Props> = (props): JSX.Element => {
       const oPrice = getPoolPriceValue(balance, poolDetails, pricePool.poolData)
       const label = FP.pipe(
         oPrice,
-        O.map((price) => formatAssetAmountCurrency({ amount: baseToAsset(price), asset: pricePool.asset, decimal: 3 })),
+        O.map((price) => {
+          if (isEthAsset(balance.asset)) {
+            price.decimal = ETH_DECIMAL
+          }
```
Comment (veado) [inline src/renderer/components/wallet/assets/AssetsTableCollapsable.tsx:151]: Pls keep in mind: If we have to do similar change for `price.decimal` at other places for ETH, extract that logic into a helper for pricing (into `getPoolPriceValue` in this case) - just to use same logic everywhere then ...

**Review by veado — APPROVED** [review]

File: src/renderer/components/wallet/assets/AssetsTableCollapsable.tsx (hunk 1 above)
Comment (sarawut11) [reply src/renderer/components/wallet/assets/AssetsTableCollapsable.tsx:151]: ok 👍
