### PR TITLE
BUG: Filters aren't persistent 

### LINKED ISSUE #1132: BUG: Filters aren't persistent
# filters

When selecting filter, navigate away, come back, filter is reset. 

Persist filter selection after chosen always.

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
- moved pools filters to the pools service; refactored AssetsFilter component to receive activeFilter and setFilter props

closes #1132

### CODE REVIEW

File: src/renderer/services/midgard/pools.ts [hunk 1]
```diff
@@ -62,6 +63,15 @@ const createPoolsService = (
 ): PoolsService => {
   const midgardDefaultApi$ = FP.pipe(byzantine$, liveData.map(getMidgardDefaultApi), RxOp.shareReplay(1))
 
+  const { get$: poolsFilters$, set: internalSetPoolsFilter, get: internalGetPoolsFilter } = observableState<
```
Comment (veado) [inline src/renderer/services/midgard/pools.ts:66]: [nitpick] `internalSetPoolsFilter` -> `_setPoolsFilter` Just to keep same naming convention for "private" things.

**Review by veado — APPROVED** [review]

**Review by veado — APPROVED** [review]
