### PR TITLE
[Swap] cache (store) previously successfully loaded fees

### LINKED ISSUE #1314: [Swap] cache (store) previously successfully loaded fees
right now when any swap amount is changed we have re-loading of fees. fees' pending state leads to the incorrect re-calculating of `max amount to swap`. 

https://user-images.githubusercontent.com/67793194/114514219-b77b8700-9c43-11eb-8f06-b4ff872fe752.mov

### PR DESCRIPTION
**Pull request by thatStrangeGuyThorchain**
- Swap.tsx: added caching of previously successfully loaded fees
closes #1314

### CODE REVIEW

File: src/renderer/components/swap/Swap.tsx [hunk 1]
```diff
@@ -280,9 +280,18 @@ export const Swap = ({
   const chainFees$ = useMemo(() => fees$, [fees$])
   const approveFees$ = useMemo(() => approveFee$, [approveFee$])
 
+  const chainFeesORef = useRef<O.Option<SwapFees>>(O.none)
```
Comment (veado) [inline src/renderer/components/swap/Swap.tsx:283]: [nitpick] `chainFeesORef` -> `prevChainFees` (just to have similar naming as we have at other places)

File: src/renderer/components/swap/Swap.tsx [hunk 2]
```diff
@@ -340,7 +349,8 @@ export const Swap = ({
     async (asset: Asset) => {
       // update `pendingSwitchAssets` state
       setPendingSwitchAssets(true)
-
+      // Reset previously stored fees
+      chainFeesORef.current = O.none
```
Comment (veado) [inline src/renderer/components/swap/Swap.tsx:353]: Not in `reset()` ^?

Comment (thatStrangeGuyThorchain) [reply src/renderer/components/swap/Swap.tsx:353]: i believe no need to do it `reset` method. this `ref`'s value stores last successfully loaded fees for source asset and i suppose we need to reset it only in case `sourceAsset` was changed. `reset` method is called also when target asset is changed and there is no need to reset cached fee value i suppose

**Review by veado — APPROVED** [review]
Cool!
