### PR TITLE
Fix route handling in case of network switch

### LINKED ISSUE #1294: Manage Pools Redirect
When clicking manage pools for specific liquidity pools, it redirects to the pool page instead of the add/withdraw liquidity page. 

image

Windows v0.1.0 -alpha2

### PR DESCRIPTION
**Pull request by veado**
- [x] Fixes #1294 
- [x] Extract handling of re-directs from `PoolsView` and  `WalletView` into `Header` ([this comment explains](https://github.com/thorchain/asgardex-electron/pull/1298/files#diff-f561f8ec69c35b3156218582c4199bbcdb136e713a29e4bfcda6f322b66bd1efR77-R87) why this change was needed)
- [x] Remove `shareReply` + `O.filter` from misc. pool services to fix memory (requests) leaks  to get data for PoolsDetailViews while switching `network`
- [x] Rename `HeaderNetwork` -> `HeaderNetworkSelector`

### CODE REVIEW

File: src/renderer/components/header/Header.tsx [hunk 1]
```diff
@@ -47,6 +50,58 @@ export const Header: React.FC = (): JSX.Element => {
...
+    poolsRoutes.swap.template
+  ])
+
+  // Check wallet sub routes  needed to re-direct in case of network switch
+  const isWalletSubRoute = useRouteMatch([
+    walletRoutes.send.template,
+    walletRoutes.upgradeBnbRune.template,
+    walletRoutes.assetDetail.template,
+    walletRoutes.bonds.template,
+    walletRoutes.bonds.template,
```
Comment (veado) [inline src/renderer/components/header/Header.tsx:68]: Duplicated ^

File: src/renderer/views/pool/PoolDetailsView.tsx [hunk 2]
```diff
@@ -60,6 +60,7 @@ export const PoolDetailsView: React.FC = () => {
     setSelectedPoolAsset(oRouteAsset)
     // Reset selectedPoolAsset on view's unmount to avoid effects with depending streams
     return () => {
+      console.log('PoolDetailsView: onLeave')
```
Comment (chaindbkey) [inline src/renderer/views/pool/PoolDetailsView.tsx:63]: clean up ^

**Review by chaindbkey — APPROVED** [review]
Looks good, just a small comment
