### PR TITLE
Fix fee of freeze/unfreeze

### LINKED ISSUE #382: Fix fee amount for freeze / unfreeze
Use `tokensFreeze` (instead of `send`) freeze amount provided by API ([testnet](https://testnet-dex.binance.org/api/v1/fees) / [mainnet](https://dex.binance.org/api/v1/fees))

### PR DESCRIPTION
**Pull request by veado**
Fixes #382

### CODE REVIEW

File: src/renderer/services/binance/service.ts [hunk 1]
```diff
@@ -342,7 +350,20 @@ const transferFees$: Observable<TransferFeesRD> = fees$.pipe(
...
+)
+
+/**
+ * Amount of feeze `Fee`
+ */
+const freezeFee$: Observable<FeeRD> = fees$.pipe(
+  map((fees) =>
+    FP.pipe(
+      fees,
+      RD.chain((fee) => RD.fromEither(getFreezeFee(fee)))
```
Comment (thatStrangeGuyThorchain) [inline src/renderer/services/binance/service.ts:366]: same with `liveData`
```ts
pipe(
  fees$,
  liveData.map(getFreezeFee),
  liveData.chain(liveData.fromEither),
  shareReplay(1)
)
```

**Review by thatStrangeGuyThorchain — APPROVED** [review]
